Repository Qbeast-io/qbeast-spark, pull requests merged in 2022-03, with the labels that each got.

#82 Releases on Sonatype and Maven Central
  build.sbt
  project/plugins.sbt
Labels: enhancement

#85 Replace `result` with `resultInternal` for `CubeWeights`
  core/src/main/scala/io/qbeast/core/model/CubeWeights.scala
  core/src/test/scala/io/qbeast/core/model/CubeWeightsBuilderTest.scala
Labels: bug

#88 Generate scaladocs for qbeastCore and qbeastSpark projects
  build.sbt
  project/build.properties
  project/plugins.sbt
Labels: documentation

#87 Documentation Improvements
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CONTRIBUTING.md
  README.md
  docs/FAQ.md
  docs/IndexMetrics.md
  docs/QbeastTable.md
Labels: documentation

#90 Headers and footers for scaladoc generation, including version in HTML
  build.sbt
Labels: documentation, low

#97 Remove "project packaging" from README, as it is now available in Maven
  CONTRIBUTING.md
  README.md
Labels: documentation
